# Generated by Django 2.1.7 on 2019-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(default='<项目名称>', help_text='项目名称', max_length=40)),
                ('编号', models.CharField(blank=True, default='<项目编号>', help_text='项目编号， 由实验室决定是否使用', max_length=40)),
                ('摘要', models.TextField(default='<项目摘要>', help_text='项目摘要')),
                ('介绍', models.TextField(default='<项目介绍>', help_text='项目介绍')),
                ('创建时间', models.DateTimeField(default='2019-01-01 00:00:00', help_text='项目创建时间')),
            ],
        ),
    ]
