# Generated by Django 2.1.7 on 2019-08-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('生产商', models.CharField(help_text='厂家名称', max_length=100)),
                ('型号', models.CharField(help_text='设备型号', max_length=100)),
                ('版本号', models.CharField(help_text='设备版本号', max_length=100)),
                ('配置文件', models.TextField(help_text='设备驱动配置文件')),
                ('驱动文件名', models.CharField(help_text='驱动文件名', max_length=100)),
                ('注册时间', models.DateTimeField(default='2019-01-01 00:00:00', help_text='设备驱动创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneDeviceType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='设备类型名', max_length=100)),
                ('description', models.TextField(help_text='设备类型描述')),
            ],
        ),
        migrations.AddField(
            model_name='planedevice',
            name='type',
            field=models.ForeignKey(help_text='设备代码', on_delete=django.db.models.deletion.CASCADE, to='storage.PlaneDeviceType'),
        ),
    ]
