# Generated by Django 2.1.7 on 2019-08-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190810_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planedevice',
            old_name='注册时间',
            new_name='create_datetime',
        ),
        migrations.RenameField(
            model_name='planedevice',
            old_name='驱动文件名',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='planedevice',
            old_name='型号',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='planedevice',
            old_name='配置文件',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='planedevice',
            old_name='生产商',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='planedevice',
            old_name='版本号',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='创建时间',
            new_name='create_datetime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='介绍',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='名称',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='编号',
            new_name='sn',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='摘要',
            new_name='subscript',
        ),
    ]
