# Generated by Django 2.1.7 on 2019-08-11 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20190811_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 4, 32, 18, 446115, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
    ]
