# Generated by Django 2.1.7 on 2019-08-11 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20190811_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneDeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(help_text='操作说明', max_length=100)),
                ('operation_datetime', models.DateTimeField(default=datetime.datetime(2019, 8, 11, 8, 15, 52, 79195, tzinfo=utc), help_text='操作时间')),
                ('origin_path', models.TextField(help_text='原始文件路径')),
                ('target_path', models.TextField(help_text='最终文件路径')),
            ],
        ),
        migrations.RenameField(
            model_name='planedevice',
            old_name='profile',
            new_name='conf',
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 8, 15, 52, 79195, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
    ]
