# Generated by Django 2.1.7 on 2019-08-11 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20190811_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(default='', help_text='旧的项目状态', max_length=100)),
                ('new_status', models.CharField(default='', help_text='新的项目状态', max_length=100)),
                ('change_datetime', models.DateTimeField(default=datetime.datetime(2019, 8, 11, 13, 46, 50, 826934, tzinfo=utc), help_text='切换时间')),
                ('comment', models.TextField(default='', help_text='状态切换的备注')),
            ],
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 13, 46, 50, 825933, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 13, 46, 50, 825933, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sn',
            field=models.CharField(default='无', help_text='项目编号， 由实验室决定是否使用', max_length=40),
        ),
        migrations.AddField(
            model_name='projectstatelog',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, to='storage.Project'),
        ),
    ]
