# Generated by Django 2.1.7 on 2019-08-11 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20190811_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 14, 10, 50, 508749, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 14, 10, 50, 509774, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 14, 10, 50, 509774, tzinfo=utc), help_text='切换时间'),
        ),
    ]
