# Generated by Django 2.2.4 on 2019-08-12 03:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20190811_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bms_id',
            field=models.IntegerField(default=-1, help_text='BMSID'),
        ),
        migrations.AddField(
            model_name='project',
            name='cd_id',
            field=models.IntegerField(default=-1, help_text='充放电机ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='cm_id',
            field=models.IntegerField(default=-1, help_text='水冷机ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='ec_id',
            field=models.IntegerField(default=-1, help_text='环境箱ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='sp_id',
            field=models.IntegerField(default=-1, help_text='振动台ID'),
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 3, 28, 5, 843894, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 3, 28, 5, 844257, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 3, 28, 5, 844565, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 3, 28, 5, 844992, tzinfo=utc), help_text='切换时间'),
        ),
    ]
