# Generated by Django 2.2.4 on 2019-08-13 02:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20190812_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bms_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cd_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cm_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ec_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sp_id',
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 2, 38, 0, 285441, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 2, 38, 0, 285801, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 2, 38, 0, 286102, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 2, 38, 0, 286451, tzinfo=utc), help_text='切换时间'),
        ),
        migrations.CreateModel(
            name='ProjectWithDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(help_text='设备', on_delete=django.db.models.deletion.CASCADE, to='storage.PlaneDevice')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, to='storage.Project')),
            ],
        ),
    ]
