# Generated by Django 2.2.4 on 2019-08-15 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20190813_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='planedevice',
            name='ps_uuid',
            field=models.CharField(default='', help_text='驱动定位/进程定位', max_length=100),
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 1, 45, 30, 912879, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 1, 45, 30, 913313, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 1, 45, 30, 913659, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 1, 45, 30, 914066, tzinfo=utc), help_text='切换时间'),
        ),
    ]
