# Generated by Django 2.2.4 on 2019-08-16 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_auto_20190815_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 1, 9, 20, 817178, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 1, 9, 20, 817554, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 1, 9, 20, 817857, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 1, 9, 20, 818233, tzinfo=utc), help_text='切换时间'),
        ),
    ]
