# Generated by Django 2.2.4 on 2019-08-30 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_auto_20190816_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 1, 26, 35, 97007, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 1, 26, 35, 98167, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 1, 26, 35, 98635, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 1, 26, 35, 99182, tzinfo=utc), help_text='切换时间'),
        ),
        migrations.CreateModel(
            name='PlaneDefaultDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2019, 8, 30, 1, 26, 35, 97596, tzinfo=utc), help_text='设置为默认设备的日期时间')),
                ('device', models.ForeignKey(help_text='设备', on_delete=django.db.models.deletion.CASCADE, to='storage.PlaneDevice')),
                ('type', models.ForeignKey(help_text='设备代码', on_delete=django.db.models.deletion.CASCADE, to='storage.PlaneDeviceType')),
            ],
        ),
    ]
