# Generated by Django 2.2.4 on 2019-08-31 02:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_auto_20190830_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planedefaultdevice',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 19, 17, 25092, tzinfo=utc), help_text='设置为默认设备的日期时间'),
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 19, 17, 24518, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 19, 17, 25553, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 19, 17, 25970, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 19, 17, 26403, tzinfo=utc), help_text='切换时间'),
        ),
        migrations.CreateModel(
            name='ProjectFlowFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1.0', help_text='流程文件版本', max_length=100)),
                ('name', models.CharField(default='', help_text='流程名', max_length=100)),
                ('full_path', models.CharField(default='', help_text='流程文件存储路径', max_length=1000)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 19, 17, 27356, tzinfo=utc), help_text='流程创建时间')),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 19, 17, 27377, tzinfo=utc), help_text='流程更新时间')),
                ('project', models.ForeignKey(help_text='关联的项目', on_delete=django.db.models.deletion.CASCADE, to='storage.Project')),
            ],
        ),
    ]
