# Generated by Django 2.2.4 on 2019-08-31 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_auto_20190831_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1.0', help_text='流程文件版本', max_length=100)),
                ('origin_name', models.CharField(default='', help_text='原始流程文件名', max_length=100)),
                ('name', models.CharField(default='', help_text='流程文件名', max_length=100)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 24, 0, 320994, tzinfo=utc), help_text='流程创建时间')),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 24, 0, 321018, tzinfo=utc), help_text='流程更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWithFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.ForeignKey(help_text='关联的流程文件', on_delete=django.db.models.deletion.CASCADE, to='storage.FlowFile')),
            ],
        ),
        migrations.AlterField(
            model_name='planedefaultdevice',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 24, 0, 318545, tzinfo=utc), help_text='设置为默认设备的日期时间'),
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 24, 0, 317921, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 24, 0, 319055, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 24, 0, 319507, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 24, 0, 319977, tzinfo=utc), help_text='切换时间'),
        ),
        migrations.DeleteModel(
            name='ProjectFlowFile',
        ),
        migrations.AddField(
            model_name='projectwithflow',
            name='project',
            field=models.ForeignKey(help_text='关联的项目', on_delete=django.db.models.deletion.CASCADE, to='storage.Project'),
        ),
    ]
