# Generated by Django 2.2.4 on 2019-09-02 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_auto_20190902_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowfile',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 30922, tzinfo=utc), help_text='流程创建时间'),
        ),
        migrations.AlterField(
            model_name='flowfile',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 30937, tzinfo=utc), help_text='流程更新时间'),
        ),
        migrations.AlterField(
            model_name='planedefaultdevice',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 29318, tzinfo=utc), help_text='设置为默认设备的日期时间'),
        ),
        migrations.AlterField(
            model_name='planedevice',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 28931, tzinfo=utc), help_text='设备驱动创建时间'),
        ),
        migrations.AlterField(
            model_name='planedevicehistory',
            name='operation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 29717, tzinfo=utc), help_text='操作时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 30012, tzinfo=utc), help_text='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectstatelog',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 30320, tzinfo=utc), help_text='切换时间'),
        ),
        migrations.AlterField(
            model_name='projectwithflow',
            name='bind_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 8, 27, 56, 31233, tzinfo=utc), help_text='绑定时间'),
        ),
    ]
