# Generated by Django 2.2.4 on 2019-09-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0028_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='show_count',
            field=models.IntegerField(default=1, help_text='最大显示次数'),
        ),
    ]
