# Generated by Django 2.2.4 on 2019-09-08 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0029_message_show_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expire_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 23, 59, 59, 999, tzinfo=utc), help_text='过期时间'),
        ),
    ]
